### ISSUE TITLE
[Bug] Making bot less error prone to disconnects from discord servers.

### ISSUE THREAD

**Issue by Videonauth** [Videonauth/ProtonDB-Bot#7]
When discord servers are disconnection from their side the bot currently gets stuck with an error message and no chance to recover from this state.

**Comment by Videonauth** [comment]
Example of an usual error message.
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/michael/.local/lib/python3.6/site-packages/aiohttp/client.py", line 202, in _request
    yield from resp.start(conn, read_until_eof)
  File "/home/michael/.local/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 640, in start
    message = yield from httpstream.read()
  File "/home/michael/.local/lib/python3.6/site-packages/aiohttp/streams.py", line 641, in read
    result = yield from super().read()
  File "/home/michael/.local/lib/python3.6/site-packages/aiohttp/streams.py", line 476, in read
    yield from self._waiter
aiohttp.errors.ServerDisconnectedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./bot-old.py", line 488, in <module>
    bot_client.run(BOT_TOKEN)
  File "/home/michael/.local/lib/python3.6/site-packages/discord/client.py", line 519, in run
    self.loop.run_until_complete(self.start(*args, **kwargs))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/michael/.local/lib/python3.6/site-packages/discord/client.py", line 491, in start
    yield from self.connect()
  File "/home/michael/.local/lib/python3.6/site-packages/discord/client.py", line 452, in connect
    self.ws = yield from DiscordWebSocket.from_client(self, resume=resume)
  File "/home/michael/.local/lib/python3.6/site-packages/discord/gateway.py", line 203, in from_client
    gateway = yield from client.http.get_gateway()
  File "/home/michael/.local/lib/python3.6/site-packages/discord/http.py", line 633, in get_gateway
    data = yield from self.request(Route('GET', '/gateway'))
  File "/home/michael/.local/lib/python3.6/site-packages/discord/http.py", line 137, in request
    r = yield from self.session.request(method, url, **kwargs)
  File "/home/michael/.local/lib/python3.6/site-packages/aiohttp/client.py", line 555, in __iter__
    resp = yield from self._coro
  File "/home/michael/.local/lib/python3.6/site-packages/aiohttp/client.py", line 209, in _request
    raise aiohttp.ClientResponseError() from exc
aiohttp.errors.ClientResponseError
```

**Comment by Videonauth** [comment]
Another Example of an usual error message.
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/michael/.local/lib/python3.6/site-packages/aiohttp/client.py", line 202, in _request
    yield from resp.start(conn, read_until_eof)
  File "/home/michael/.local/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 640, in start
    message = yield from httpstream.read()
  File "/home/michael/.local/lib/python3.6/site-packages/aiohttp/streams.py", line 641, in read
    result = yield from super().read()
  File "/home/michael/.local/lib/python3.6/site-packages/aiohttp/streams.py", line 476, in read
    yield from self._waiter
aiohttp.errors.ServerDisconnectedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./bot-old.py", line 488, in <module>
    bot_client.run(BOT_TOKEN)
  File "/home/michael/.local/lib/python3.6/site-packages/discord/client.py", line 519, in run
    self.loop.run_until_complete(self.start(*args, **kwargs))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/michael/.local/lib/python3.6/site-packages/discord/client.py", line 491, in start
    yield from self.connect()
  File "/home/michael/.local/lib/python3.6/site-packages/discord/client.py", line 452, in connect
    self.ws = yield from DiscordWebSocket.from_client(self, resume=resume)
  File "/home/michael/.local/lib/python3.6/site-packages/discord/gateway.py", line 203, in from_client
    gateway = yield from client.http.get_gateway()
  File "/home/michael/.local/lib/python3.6/site-packages/discord/http.py", line 633, in get_gateway
    data = yield from self.request(Route('GET', '/gateway'))
  File "/home/michael/.local/lib/python3.6/site-packages/discord/http.py", line 137, in request
    r = yield from self.session.request(method, url, **kwargs)
  File "/home/michael/.local/lib/python3.6/site-packages/aiohttp/client.py", line 555, in __iter__
    resp = yield from self._coro
  File "/home/michael/.local/lib/python3.6/site-packages/aiohttp/client.py", line 209, in _request
    raise aiohttp.ClientResponseError() from exc
aiohttp.errors.ClientResponseError
Exception ignored in: <bound method ClientSession.__del__ of <aiohttp.client.ClientSession object at 0x7f4058bfc8d0>>
Traceback (most recent call last):
  File "/home/michael/.local/lib/python3.6/site-packages/aiohttp/client.py", line 93, in __del__
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1316, in call_exception_handler
  File "/usr/lib/python3.6/logging/__init__.py", line 1337, in error
  File "/usr/lib/python3.6/logging/__init__.py", line 1444, in _log
  File "/usr/lib/python3.6/logging/__init__.py", line 1454, in handle
  File "/usr/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
  File "/usr/lib/python3.6/logging/__init__.py", line 865, in handle
  File "/usr/lib/python3.6/logging/__init__.py", line 1071, in emit
  File "/usr/lib/python3.6/logging/__init__.py", line 1061, in _open
NameError: name 'open' is not defined
Exception ignored in: <bound method BaseEventLoop.call_exception_handler of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1316, in call_exception_handler
  File "/usr/lib/python3.6/logging/__init__.py", line 1337, in error
  File "/usr/lib/python3.6/logging/__init__.py", line 1444, in _log
  File "/usr/lib/python3.6/logging/__init__.py", line 1454, in handle
  File "/usr/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
  File "/usr/lib/python3.6/logging/__init__.py", line 865, in handle
  File "/usr/lib/python3.6/logging/__init__.py", line 1071, in emit
  File "/usr/lib/python3.6/logging/__init__.py", line 1061, in _open
NameError: name 'open' is not defined

```

**Comment by Videonauth** [comment]
Removing this from the milestone, because testing fixes might take a while to have the exact errors showing up again.

**Comment by Videonauth** [comment]
This is likely to be an obsolete issue after the complete rework of the search function.
